apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- secret.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: flowise-aws-sdk-patch
  files:
  - remove-x-amz-tagging.cjs
