apiVersion: v1
kind: Service
metadata:
  name: flowise-service
  namespace: default
  labels:
    app: flowise
spec:
  type: ClusterIP
  selector:
    app: flowise
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
