apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: litellm-secrets
stringData:
  OPENAI_API_KEY: 'Your_OpenAI_API_Key_Here'
  LITELLM_MASTER_KEY: 'sk-Your_LiteLLM_Master_Key_Here'
  LITELLM_SALT_KEY: 'salt-Your_LiteLLM_Salt_Key_Here'
  DATABASE_URL: 'postgresql://litellm:password@postgres:5432/litellm'
