apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-config
  namespace: default
data:
  TZ: Asia/Tokyo
  LOG_LEVEL: INFO
  LOG_OUTPUT_FORMAT: text
  EDITION: SELF_HOSTED
  DEPLOY_ENV: PRODUCTION
  CONSOLE_API_URL: https://dify.kachigo.jp
  CONSOLE_WEB_URL: https://dify.kachigo.jp
  SERVICE_API_URL: https://dify.kachigo.jp
  APP_API_URL: https://dify.kachigo.jp
  APP_WEB_URL: https://dify.kachigo.jp
  FILES_URL: https://dify.kachigo.jp
  INTERNAL_FILES_URL: http://dify-api-service:5001
  TRIGGER_URL: https://dify.kachigo.jp
  NEXT_PUBLIC_SOCKET_URL: wss://dify.kachigo.jp
  DIFY_BIND_ADDRESS: 0.0.0.0
  DIFY_PORT: "5001"
  SERVER_WORKER_AMOUNT: "1"
  SERVER_WORKER_CLASS: gevent
  GUNICORN_TIMEOUT: "200"
  CELERY_WORKER_CLASS: gevent
  WEB_API_CORS_ALLOW_ORIGINS: https://dify.kachigo.jp
  CONSOLE_CORS_ALLOW_ORIGINS: https://dify.kachigo.jp
  DB_HOST: cloudsql-proxy
  DB_PORT: "5432"
  DB_USERNAME: dify-user
  DB_DATABASE: dify
  SQLALCHEMY_POOL_SIZE: "30"
  SQLALCHEMY_MAX_OVERFLOW: "10"
  REDIS_HOST: dify-redis-service
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_DB: "0"
  VECTOR_STORE: pgvector
  PGVECTOR_HOST: cloudsql-proxy
  PGVECTOR_PORT: "5432"
  PGVECTOR_USER: dify-user
  PGVECTOR_DATABASE: dify
  PGVECTOR_MIN_CONNECTION: "1"
  PGVECTOR_MAX_CONNECTION: "5"
  STORAGE_TYPE: opendal
  OPENDAL_SCHEME: fs
  OPENDAL_FS_ROOT: storage
  PLUGIN_DAEMON_URL: http://dify-plugin-daemon-service:5002
  PLUGIN_DIFY_INNER_API_URL: http://dify-api-service:5001
  PLUGIN_REMOTE_INSTALLING_HOST: 0.0.0.0
  PLUGIN_REMOTE_INSTALLING_PORT: "5003"
  PLUGIN_MAX_PACKAGE_SIZE: "52428800"
  PLUGIN_PPROF_ENABLED: "false"
  PLUGIN_DEBUGGING_HOST: 0.0.0.0
  PLUGIN_DEBUGGING_PORT: "5003"
  MARKETPLACE_ENABLED: "true"
  MARKETPLACE_API_URL: https://marketplace.dify.ai
  MARKETPLACE_URL: https://marketplace.dify.ai
  CODE_EXECUTION_ENDPOINT: http://dify-sandbox-service:8194
  SANDBOX_PORT: "8194"
  SANDBOX_WORKER_TIMEOUT: "15"
  SANDBOX_ENABLE_NETWORK: "true"
  SANDBOX_HTTP_PROXY: http://dify-ssrf-proxy-service:3128
  SANDBOX_HTTPS_PROXY: http://dify-ssrf-proxy-service:3128
  DIFY_AGENT_PLUGIN_DAEMON_URL: http://dify-plugin-daemon-service:5002
  DIFY_AGENT_INNER_API_URL: http://dify-api-service:5001
  DIFY_AGENT_SHELLCTL_ENTRYPOINT: http://dify-agent-backend-service:5050
  SSRF_HTTP_PORT: "3128"
  SSRF_REVERSE_PROXY_PORT: "8194"
  SSRF_SANDBOX_HOST: dify-sandbox-service
  SSRF_DEFAULT_TIME_OUT: "5"
  SSRF_DEFAULT_CONNECT_TIME_OUT: "5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-ssrf-proxy-config
  namespace: default
data:
  squid.conf: |
    acl localnet src 10.0.0.0/8
    acl localnet src 172.16.0.0/12
    acl localnet src 192.168.0.0/16
    acl SSL_ports port 443
    acl Safe_ports port 80
    acl Safe_ports port 443
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localnet
    http_access deny all
    http_port 3128
    coredump_dir /var/spool/squid
