apiVersion: v1
kind: Secret
metadata:
  name: dify-secret
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: "replace-with-openssl-rand-base64-42"
  DB_PASSWORD: "replace-with-postgres-password"
  PGVECTOR_PASSWORD: "replace-with-postgres-password"
  REDIS_PASSWORD: "replace-with-redis-password"
  INIT_PASSWORD: "replace-with-initial-admin-password"
  PLUGIN_DIFY_INNER_API_KEY: "replace-with-openssl-rand-base64-42"
  PLUGIN_DAEMON_KEY: "replace-with-openssl-rand-base64-42"
  DIFY_AGENT_PLUGIN_DAEMON_API_KEY: "replace-with-openssl-rand-base64-42"
  DIFY_AGENT_INNER_API_KEY: "replace-with-openssl-rand-base64-42"
  DIFY_AGENT_SERVER_SECRET_KEY: "replace-with-openssl-rand-base64-42"
  SANDBOX_API_KEY: "replace-with-openssl-rand-base64-42"
  CODE_EXECUTION_API_KEY: "replace-with-same-value-as-sandbox-api-key"
