apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-deployment-image-updater
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["bcx-hp-host-prod"]
    verbs: ["get", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]