apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: default
type: Opaque
data:
  N8N_ENCRYPTION_KEY: "replace-with-strong-encryption-key"
  DB_POSTGRESDB_PASSWORD: "replace-with-strong-encryption-key"
