apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
  namespace: keycloak
  annotations:
    cloud.google.com/load-balancer-type: "Internal"  # Private load balancer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
