apiVersion: v1
kind: Secret
metadata:
  name: affine-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: "base64-encoded-postgres-password"
  REDIS_SERVER_PASSWORD: "base64-encoded-redis-password"
