apiVersion: v1
kind: Secret
metadata:
  name: bcx-hp-host-secret
type: Opaque
data:
  NEXT_PUBLIC_STRAPI_TOKEN: "<base64_encoded_token_here>"
  GOOGLE_CLIENT_SECRET: "<base64_encoded_token_here>"
  GOOGLE_REFRESH_TOKEN: "<base64_encoded_token_here>"
  GOOGLE_SHEET_ID: "<base64_encoded_token_here>"
  GOOGLE_DRIVE_FOLDER_ID: "<base64_encoded_token_here>"
  GMAIL_APP_PASSWORD: "<base64_encoded_token_here>"
