apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kachigo-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - n8n.kachigo.jp
    - flowise.kachigo.jp
    - browserless.kachigo.jp
    - directus.kachigo.jp
    - dify.kachigo.jp
    secretName: kachigo-tls-secret
  rules:
  - host: n8n.kachigo.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-service
            port:
              number: 80
  - host: flowise.kachigo.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flowise-service
            port:
              number: 80
  - host: dify.kachigo.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dify-service
            port:
              number: 80
  - host: browserless.kachigo.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: browserless-service
            port:
              number: 3000
  - host: directus.kachigo.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: directus-service
            port:
              number: 80
  - host: keycloak.kachigo.jp
    http:
      paths:
      - backend:
          service:
            name: keycloak-service
            port:
              number: 80
        path: /
        pathType: Prefix
