apiVersion: v1
kind: ConfigMap
metadata:
  name: bcx-strapi-config
data:
  NODE_ENV: "development"
  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: "cloudsql-proxy"
  DATABASE_NAME: "banchanxanh"
  DATABASE_PORT: "5432"
  HOST: "0.0.0.0"
  PORT: "1337"
