apiVersion: v1
kind: ConfigMap
metadata:
  name: bcx-strapi-config
data:
  NODE_ENV: "development"
  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: "cloudsql-proxy"
  DATABASE_NAME: "banchanxanh"
  DATABASE_PORT: "5432"
  HOST: "0.0.0.0"
  PORT: "1337"
  S3_BUCKET: "replace-with-b2-bucket-name"
  S3_REGION: "replace-with-b2-region"
  S3_ENDPOINT: "https://s3.replace-with-b2-region.backblazeb2.com"
  S3_ACL: "public-read"
  S3_FORCE_PATH_STYLE: "false"
  S3_SIGNED_URL_EXPIRES: "900"
