apiVersion: v1
kind: Service
metadata:
  name: browserless-service
  namespace: default
  labels:
    app: browserless
spec:
  type: ClusterIP
  selector:
    app: browserless
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
