apiVersion: v1
kind: ConfigMap
metadata:
  name: bcx-strapi-config
data:
  NODE_ENV: "<environment_here>"
  DATABASE_CLIENT: "<database_client_here>"
  DATABASE_HOST: "<database_host_here>"
  DATABASE_NAME: "<database_name_here>"
  DATABASE_PORT: "<database_port_here>"
  HOST: "<host_here>"
  PORT: "<port_here>"
  S3_BUCKET: "<b2_bucket_name_here>"
  S3_REGION: "<b2_region_here>"
  S3_ENDPOINT: "https://s3.<b2_region_here>.backblazeb2.com"
  S3_ACL: "public-read"
  S3_FORCE_PATH_STYLE: "false"
  S3_SIGNED_URL_EXPIRES: "900"
