apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcx-strapi
  labels:
    app: bcx-strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcx-strapi
  template:
    metadata:
      labels:
        app: bcx-strapi
    spec:
      containers:
      - name: bcx-strapi
        image: us-central1-docker.pkg.dev/banchanxanh/bcx-strapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
          protocol: TCP
        envFrom:
        - configMapRef:
            name: bcx-strapi-config
        - secretRef:
            name: bcx-strapi-secret
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
