apiVersion: v1
kind: Secret
metadata:
  name: bcx-strapi-secret
type: Opaque
data:
  ADMIN_JWT_SECRET: "<base64_encoded_token_here>"
  API_TOKEN_SALT: "<base64_encoded_token_here>"
  APP_KEYS: "<base64_encoded_token_here>"
  DATABASE_PASSWORD: "<base64_encoded_token_here>"
  DATABASE_USERNAME: "<base64_encoded_token_here>"
  ENCRYPTION_KEY: "<base64_encoded_token_here>"
  JWT_SECRET: "<base64_encoded_token_here>"
  TRANSFER_TOKEN_SALT: "<base64_encoded_token_here>"
