apiVersion: v1
kind: ConfigMap
metadata:
  name: bcx-strapi-config
data:
  NODE_ENV: "production"
  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: "ep-delicate-frost-ajuljjor-pooler.c-3.us-east-2.aws.neon.tech"
  DATABASE_NAME: "banchanxanh"
  DATABASE_PORT: "5432"
  DATABASE_SSL: "true"
  HOST: "0.0.0.0"
  PORT: "1337"
  UPLOAD_PROVIDER: "aws-s3"
  CDN_ROOT_PATH: "uploads"
  B2_REGION: "us-east-005"
  B2_BASE_URL: "https://cdn.banchanxanh.com"
  B2_ENDPOINT: "https://s3.us-east-005.backblazeb2.com"
  B2_SIGNED_URL_EXPIRES: "3600"
  B2_BUCKET_NAME: "banchanxanh"
