apiVersion: v1
kind: ConfigMap
metadata:
  name: directus-config
  namespace: default
data:
  PUBLIC_URL: https://directus.kachigo.jp
  LOG_LEVEL: info
  TELEMETRY: "false"
  CORS_ENABLED: "true"
  CORS_ORIGIN: https://directus.kachigo.jp
  DB_CLIENT: pg
  DB_HOST: cloudsql-proxy
  DB_PORT: "5432"
  DB_DATABASE: directus
  DB_USER: directus-user
  DB_SSL: "false"
  AI_ENABLED: "true"
  STORAGE_LOCATIONS: s3
  STORAGE_S3_DRIVER: s3
  STORAGE_S3_BUCKET: kachigo-directus
  STORAGE_S3_REGION: us-east-005
  STORAGE_S3_ENDPOINT: https://s3.us-east-005.backblazeb2.com
  STORAGE_S3_FORCE_PATH_STYLE: "true"
  FILES_MAX_UPLOAD_SIZE: 20mb
