apiVersion: v1
kind: Secret
metadata:
  name: directus-secret
  namespace: default
type: Opaque
data:
  SECRET: replace-with-openssl-rand-hex-32
  DB_PASSWORD: replace-with-postgres-password
  STORAGE_S3_KEY: replace-with-b2-key-id
  STORAGE_S3_SECRET: replace-with-b2-application-key
