swagger: "2.0"
info:
  title: "Basic API"
  description: "A basic API Gateway example"
  version: "1.0.0"
host: "gateway-id-banchanxanh.gateway.dev"
x-google-endpoints:
  - name: "gateway-id-banchanxanh.gateway.dev"
    allowCors: true

paths:
  /hello:
    get:
      summary: "Say Hello"
      description: "Returns a simple greeting message"
      operationId: hello
      x-google-backend:
        address: "https://google.com"
      responses:
        '200':
          description: "A successful response"
          schema:
            type: "string"
